### ISSUE TITLE
db - node.js 연결 문제

### ISSUE THREAD

**Issue by mina-dong** [LovellR/GSS_Project#49]
db.connect((err) => { ^ TypeError: db.connect is not a function at Object.<anonymous>

아까까지만 해도 db연결엔 문제 없었는데,
다른 database랑 연결하려고 하니 문제가 발생했습니다

두가지의 database를 연결할 순 없나요?

**Comment by mina-dong** [comment]
db.connect((err) => {
   ^

TypeError: db.connect is not a function
    at Object.<anonymous> (D:\4th\oss\GSS_Project\oss-project\src\server\config\db.js:10:4)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (D:\4th\oss\GSS_Project\oss-project\src\server\server.js:4:12)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)

**Comment by mina-dong** [comment]
이것도 다중 데이터베이스를 사용하려고 하니까 생긴문제인거 같습니다. 테이블 이동하여 
01:36:20	alter table osbp.병용금기약물 rename pharmacy_db.병용금기약물	0 row(s) affected	0.343 sec
으로 해결하여 해당 이슈를 닫습니다.
