### ISSUE TITLE
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client

### ISSUE THREAD

**Issue by mina-dong** [LovellR/GSS_Project#52]
관련이슈: #50 

Received data:
First Medicine: 에이서
Second Medicine: 카토라
D:\4th\oss\GSS_Project\oss-project\node_modules\mysql\lib\protocol\Parser.js:437
      throw err; // Rethrow non-MySQL errors
      ^

Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:399:5)
    at ServerResponse.setHeader (node:_http_outgoing:645:11) 
    at ServerResponse.header (D:\4th\oss\GSS_Project\oss-project\node_modules\express\lib\response.js:795:10)
    at ServerResponse.send (D:\4th\oss\GSS_Project\oss-project\node_modules\express\lib\response.js:175:12)
    at ServerResponse.json (D:\4th\oss\GSS_Project\oss-project\node_modules\express\lib\response.js:279:15)
    at Query.<anonymous> (D:\4th\oss\GSS_Project\oss-project\src\server\server.js:49:13)
    at Query.<anonymous> (D:\4th\oss\GSS_Project\oss-project\node_modules\mysql\lib\Connection.js:526:10)
    at Query._callback (D:\4th\oss\GSS_Project\oss-project\node_modules\mysql\lib\Connection.js:488:16)
    at Sequence.end (D:\4th\oss\GSS_Project\oss-project\node_modules\mysql\lib\protocol\sequences\Sequence.js:83:24)      
    at Query._handleFinalResultPacket (D:\4th\oss\GSS_Project\oss-project\node_modules\mysql\lib\protocol\sequences\Query.js:149:8) {
  code: 'ERR_HTTP_HEADERS_SENT'
}

**Comment by mina-dong** [comment]
두 번으로 다르게 응답을 받아서 생긴 오류 같아요 . res.send() 부분 수정하고 해당 이슈 처리했습니다.
