### ISSUE TITLE
병용금지페이지 - Uncaught runtime errors:

### ISSUE THREAD

**Issue by mina-dong** [LovellR/GSS_Project#55]
관련이슈 #50 

Uncaught runtime errors:
×
ERROR
Cannot read properties of null (reading 'map')
TypeError: Cannot read properties of null (reading 'map')
    at Search (http://localhost:3000/static/js/bundle.js:1766:30)
    at renderWithHooks (http://localhost:3000/static/js/bundle.js:26037:22)
    at mountIndeterminateComponent (http://localhost:3000/static/js/bundle.js:30008:17)
    at beginWork (http://localhost:3000/static/js/bundle.js:31311:20)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:16293:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:16337:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:16394:35)
    at beginWork$1 (http://localhost:3000/static/js/bundle.js:36292:11)
    at performUnitOfWork (http://localhost:3000/static/js/bundle.js:35540:16)
    at workLoopSync (http://localhost:3000/static/js/bundle.js:35463:9)

테이블 TBODY 생성하고 결과 가지고 오려면 이런 오류가 발생합니다...

**Comment by mina-dong** [comment]
db.query() ,serarch.js 내 코드 수정으로 해당 이슈 처리.  map에 있어서 오류가 생긴걸로 추정됩니다.
